FORMAT: 1A
HOST: https://sit-mobile-apis.the1.co.th

# iMB.MN.10- Get badge inprogress

## Badge inprogress [/badge/status/inprogress]

### Get badge inprogress [GET]
    
+ Response 200 (application/json)

            {
                "inProgress": [
                    {
                        "id": "BDG_SEAFOOD_INPROGRESS",
                        "displayName": "Sea food achieved",
                        "newArrival": true,
                        "termsConditions": "<p>TERMS &amp; CONDITIONS</p><p> </p><p>1. Make 5 drink purchases at Segafredo within May 31, 2025 to finish the mission.</p><p> </p><p>2. Identify your The 1 membership when making purchases to record mission progress</p><p> </p><p>3. Mission progress will be updated and shown on The 1 application within 1 day after making eligible purchases </p><p> </p><p>4. Coupon will be rewarded to your account right after finishing the mission. Please find it in the &quot;&quot;My Rewards&quot;&quot; menu</p><p> </p><p>5. Activity period is 24 April - 31 May 2025</p><p> </p><p>6. Limited to 1 member per 1 privilege per 1 Month throughout the campaign </p><p> </p><p>7. The company reserves the right to change terms and conditions without prior notice.</p><p> </p><p>8. For more details please contact The 1 Call Center 0-2660-1000</p>",
                        "endingSoon": {
                            "timeToExpire": 7.0,
                            "timeUnit": "days"
                        },
                        "rules": "Make 5 drink purchases within a month",
                        "achievementText": "<p>You get a FREE Drink!  I'm thirsty could you get me drink?</p>",
                        "categories": [
                            {
                            "name": "Highlights"
                            },
                            {
                            "name": "Dining"
                            }
                        ],
                        "campaign": {
                            "endDate": "2025-05-31T16:59:59Z",
                            "name": "BDG_SEAFOOD_INPROGRESS",
                            "description": "",
                            "id": "7832",
                            "campaignReference": "",
                            "startDate": "2025-04-23T17:00:01Z",
                            "behaviors": [
                            {
                                "title": "Achieved Over all Mission",
                                "goalType": "count",
                                "id": "26984"
                            }
                            ]
                        },
                        "badgeUrl": "https://library.the1.co.th/content/dam/the1/badge/SegafredoLoverMissionImage.png",
                        "thumbnail": "https://library.the1.co.th/content/dam/the1/badge/SegafredoLoverMissionImage.png",
                        "missionType": "checklist",
                        "brand": {
                            "code": "brandcode",
                            "name": "brand name",
                            "weight": 0.0,
                            "image": "https://uatlibrary.the1.co.th/content/dam/badge/BNBChampion.png"
                        },
                        "accountingBranch": {
                            "code": "acct branch code",
                            "name": "acct branch name"
                        },
                        "branch": {
                            "code": "branch code",
                            "name": "branch name"
                        },
                        "childBadges": [
                            {
                            "id": "BDG_SEAFOOD_INPROGRESS_ONE",
                            "newArrival": false,
                            "campaign": {
                                "endDate": "2025-05-23T17:00:01Z",
                                "id": "26901",
                                "startDate": "2025-04-23T17:00:01Z",
                                "behaviors": [
                                {
                                    "title": "Stall #1 Mission Achieved",
                                    "goalType": "count",
                                    "id": "37001",
                                    "outcome": {
                                    "description": "<p>Get 1 FREE #c item from stall #1</p>",
                                    "image": "https://uatlibrary.the1.co.th/content/dam/badge/20250317_Bann_Beyond_Lucky_31.png",
                                    "expiry": "2025-05-31T23:59:00Z",
                                    "type": "Reward",
                                    "value": "13a09d046-f437-4245-af9d-f42a7dfa101c"
                                    }
                                }
                                ]
                            },
                            "brand": {},
                            "accountingBranch": {},
                            "branch": {},
                            "childBadges": []
                            },
                            {
                            "id": "BDG_SEAFOOD_INPROGRESS_TWO",
                            "newArrival": false,
                            "campaign": {
                                "endDate": "2025-05-23T17:00:01Z",
                                "id": "26912",
                                "startDate": "2025-04-23T17:00:01Z",
                                "behaviors": [
                                {
                                    "title": "Stall #2 Mission Achieved",
                                    "goalType": "count",
                                    "id": "26981",
                                    "outcome": {
                                    "description": "<p>Get 1 FREE item #c from stall #2</p>",
                                    "image": "https://uatlibrary.the1.co.th/content/dam/badge/BDGHUGESPENDERJUN.png",
                                    "expiry": "2025-05-31T23:59:00Z",
                                    "type": "Reward",
                                    "value": "53a09d046-f437-4245-af9d-f42a7dfa101c"
                                    }
                                }
                                ]
                            },
                            "brand": {},
                            "accountingBranch": {},
                            "branch": {},
                            "childBadges": []
                            }
                        ],
                        "progress": {
                            "missionType": "checklist",
                            "badgeId": "BDG_SEAFOOD_ACHIEVED",
                            "behaviorId": "26984",
                            "goalType": "count",
                            "state": "IN_PROGRESS",
                            "progress": 0.0,
                            "goal": 2.0,
                            "childProgresses": [
                                {
                                    "badgeId": "BDG_SEAFOOD_INPROGRESS_ONE",
                                    "behaviorId": "37001",
                                    "goalType": "count",
                                    "state": "IN_PROGRESS",
                                    "progress": 3.0,
                                    "goal": 10.0,
                                    "lastUpdated": "2020-06-03T02:00:00.000+00:00"
                                },
                                {
                                    "badgeId": "BDG_SEAFOOD_INPROGRESS_TWO",
                                    "behaviorId": "26981",
                                    "goalType": "spent",
                                    "state": "IN_PROGRESS",
                                    "progress": 500.0,
                                    "goal": 3000.0,
                                    "lastUpdated": "2020-06-03T02:00:00.000+00:00"
                                }
                            ]
                        },
                        "analyticsTag": "some tag text"
                        }
                ]
            }   