FORMAT: 1A
HOST: https://sit-mobile-apis.the1.co.th

# iMO.MN.01 - Claim badge

## Claim badge [/badge/claim]

### Claim badge [POST]
    
+ Response 200 (application/json)

            {
                "reward": {
                    "userOfferId": "9LmikaFDsxt4Yzr7KsGKCGA",
                    "rootOfferId": "ab2bd6c0-1a15-467d-af75-846173168dc5"
                }
            }   