FORMAT: 1A
HOST: https://sit-mobile-apis.the1.co.th

# iMB.MN.10 - Get badge status (new progress)

## Badge checklist status-1 [/badge/status?id=BDG_SEGAFREDO_LOVER_CL]

### Get Badge checklist status-1 [GET]
    
+ Response 200 (application/json)

        {
            "missionType": "checklist",
            "badgeId": "BDG_SEGAFREDO_LOVER_CL",
            "behaviorId": "26984",
            "goalType": "count",
            "state": "COMPLETED",
            "childProgresses": [
                {
                    "badgeId": "BDG_SEGAFREDO_STALL_ONE",
                    "behaviorId": "37001",
                    "goalType": "count",
                    "state": "COMPLETED",
                    "lastUpdated": "2020-06-03T02:00:00.000+00:00"
                },
                {
                    "badgeId": "BDG_SEGAFREDO_STALL_TWO",
                    "behaviorId": "26981",
                    "goalType": "count",
                    "state": "COMPLETED",
                    "lastUpdated": "2020-06-03T02:00:00.000+00:00"
                }
            ]
        }

## Badge checklist status-2 [/badge/status?id=BDG_REDEEM_CL]

### Get Badge checklist status-2 [GET]
    
+ Response 200 (application/json)

        {
            "missionType": "checklist",
            "badgeId": "BDG_REDEEM_CL",
            "behaviorId": "26984",
            "goalType": "count",
            "state": "IN_PROGRESS",
            "progress": 2.0,
            "goal": 4.0,
            "childProgresses": [
                {
                    "badgeId": "BDG_REDEEM_ONE",
                    "behaviorId": "37001",
                    "goalType": "count",
                    "state": "COMPLETED",
                    "lastUpdated": "2020-06-03T02:00:00.000+00:00"
                },
                {
                    "badgeId": "BDG_REDEEM_TWO",
                    "behaviorId": "26981",
                    "goalType": "count",
                    "state": "IN_PROGRESS",
                    "progress": 3.0,
                    "goal": 10.0,
                    "lastUpdated": "2020-06-03T02:00:00.000+00:00"
                },
                {
                    "badgeId": "BDG_REDEEM_THREE",
                    "behaviorId": "26982",
                    "goalType": "spent",
                    "state": "IN_PROGRESS",
                    "progress": 500.0,
                    "goal": 3000.0,
                    "lastUpdated": "2020-06-03T02:00:00.000+00:00"
                },
                {
                    "badgeId": "BDG_REDEEM_FOUR",
                    "behaviorId": "26983",
                    "goalType": "count",
                    "state": "ACHIEVED",
                    "lastUpdated": "2020-06-03T02:00:00.000+00:00"
                }
            ]
        }

## Badge progress status-1 [/badge/status?id=BDG_SEGAFREDO_LOVER3]

### Get Badge progress status-1 [GET]

+ Response 200 (application/json)

        {
            "missionType": "progress",
            "badgeId": "BDG_SEGAFREDO_LOVER3",
            "behaviorId": "26984",
            "goalType": "count",
            "state": "IN_PROGRESS",
            "progress": 2.0,
            "goal": 4.0,
            "lastUpdated": "2020-06-03T02:00:00.000+00:00"
        }